[package]
name = "fungible-token"
version = "1.0.0"
authors = [
  "Matthew Beekman <matthew.beekman@walc.io>",
  "Mario Reder <mario.reder@pm.me",
]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-contract-standards = "4"
near-sdk = "4"
serde = "1"
serde_json = "1"
